# quiz questions from https://opentdb.com/api_config.php


data = [
    {
        "category": "Entertainment: Board Games",
        "type": "multiple",
        "difficulty": "easy",
        "question": "In a standard game of Monopoly, what colour are the two cheapest properties?",
        "correct_answer": "Brown",
        "incorrect_answers": ["Green", "Yellow", "Blue"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The Indie Game Development Studio Cing, developers of Hotel Dusk and Last Window, went bankrupt on March 1st, 2010.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Geography",
        "type": "boolean",
        "difficulty": "medium",
        "question": "There are no roads in\/out of Juneau, Alaska.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "General Knowledge",
        "type": "multiple",
        "difficulty": "medium",
        "question": "Which of the following Ivy League universities has its official motto in Hebrew as well as in Latin?",
        "correct_answer": "Yale University",
        "incorrect_answers": [
            "Princeton University",
            "Harvard University",
            "Columbia University",
        ],
    },
    {
        "category": "Entertainment: Film",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In the original script of &quot;The Matrix&quot;, the machines used humans as additional computing power instead of batteries.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Science & Nature",
        "type": "multiple",
        "difficulty": "easy",
        "question": "What does DNA stand for?",
        "correct_answer": "Deoxyribonucleic Acid",
        "incorrect_answers": [
            "Deoxyribogenetic Acid",
            "Deoxyribogenetic Atoms",
            "Detoxic Acid",
        ],
    },
    {
        "category": "Entertainment: Film",
        "type": "multiple",
        "difficulty": "medium",
        "question": "Which one of these actors is said to be cut from the film &#039;E.T. the Extra-Terrestrial&#039;?",
        "correct_answer": "Harrison Ford",
        "incorrect_answers": [
            "Michael J. Fox",
            "Andy Kaufman",
            "Arnold Schwarzenegger",
        ],
    },
    {
        "category": "General Knowledge",
        "type": "multiple",
        "difficulty": "medium",
        "question": "What character was once considered to be the 27th letter of the alphabet?",
        "correct_answer": "Ampersand",
        "incorrect_answers": ["Interrobang", "Tilde", "Pilcrow"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "multiple",
        "difficulty": "medium",
        "question": "When was Chapter 1 of the Source Engine mod &quot;Underhell&quot; released?",
        "correct_answer": "September 1st, 2013",
        "incorrect_answers": [
            "March 3rd, 2011",
            "September 12th, 2013",
            "October 2nd, 2012",
        ],
    },
    {
        "category": "Mythology",
        "type": "multiple",
        "difficulty": "hard",
        "question": "Nidhogg is a mythical creature from what mythology?",
        "correct_answer": "Norse",
        "incorrect_answers": ["Egyptian", "Greek", "Hindu"],
    },
    # {
    #     "category": "Entertainment: Video Games",
    #     "type": "multiple",
    #     "difficulty": "easy",
    #     "question": "The name of the Metroid series comes from what?",
    #     "correct_answer": "An enemy in the game",
    #     "incorrect_answers": [
    #         "The final boss&#039;s name",
    #         "The main character&#039;s name",
    #         "A spaceship&#039;s name",
    #     ],
    # },
    # {
    #     "category": "Celebrities",
    #     "type": "multiple",
    #     "difficulty": "medium",
    #     "question": "What was the name of Marilyn Monroe&#039;s first husband?",
    #     "correct_answer": "James Dougherty",
    #     "incorrect_answers": ["Joe Dimaggio", "Kirk Douglas", "Arthur Miller"],
    # },
    # {
    #     "category": "Entertainment: Television",
    #     "type": "multiple",
    #     "difficulty": "easy",
    #     "question": "In Star Trek: The Next Generation, what is the name of Data&#039;s cat?",
    #     "correct_answer": "Spot",
    #     "incorrect_answers": ["Mittens", "Tom", "Kitty"],
    # },
    # {
    #     "category": "Entertainment: Video Games",
    #     "type": "multiple",
    #     "difficulty": "hard",
    #     "question": "Which monster in &quot;Monster Hunter Tri&quot; was causing earthquakes in Moga Village?",
    #     "correct_answer": "Ceadeus",
    #     "incorrect_answers": ["Alatreon", "Rathalos", "Lagiacrus"],
    # },
    # {
    #     "category": "Entertainment: Video Games",
    #     "type": "multiple",
    #     "difficulty": "medium",
    #     "question": "In the game &quot;Red Dead Redemption&quot;, what is the name of John Marston&#039;s dog?",
    #     "correct_answer": "Rufus",
    #     "incorrect_answers": ["Rutus", "Finn", "Apollo"],
    # },
    # {
    #     "category": "Entertainment: Video Games",
    #     "type": "multiple",
    #     "difficulty": "easy",
    #     "question": "Which of these is not a wonder weapon in &quot;Call Of Duty: Zombies&quot;?",
    #     "correct_answer": "R115 Resonator",
    #     "incorrect_answers": ["GKZ-45 Mk3", "Ray Gun", "Scavenger"],
    # },
    # {
    #     "category": "Science & Nature",
    #     "type": "multiple",
    #     "difficulty": "easy",
    #     "question": "What animal takes part in Schr&ouml;dinger&#039;s most famous thought experiment?",
    #     "correct_answer": "Cat",
    #     "incorrect_answers": ["Dog", "Bat", "Butterfly"],
    # },
    # {
    #     "category": "General Knowledge",
    #     "type": "multiple",
    #     "difficulty": "easy",
    #     "question": "What nuts are used in the production of marzipan?",
    #     "correct_answer": "Almonds",
    #     "incorrect_answers": ["Peanuts", "Walnuts", "Pistachios"],
    # },
    # {
    #     "category": "General Knowledge",
    #     "type": "multiple",
    #     "difficulty": "hard",
    #     "question": "In &quot;Battle Cats&quot;, what is Moneko \/ MISS Moneko&#039;s critical percentage rate?",
    #     "correct_answer": "15%",
    #     "incorrect_answers": ["20%", "10%", "25%"],
    # },
    # {
    #     "category": "Science & Nature",
    #     "type": "multiple",
    #     "difficulty": "easy",
    #     "question": "What is the atomic mass of Carbon?",
    #     "correct_answer": "12",
    #     "incorrect_answers": ["14", "16", "10"],
    # },
]
